### ISSUE TITLE
Check requirements of `imageio_ffmpeg`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#118]

**Comment by tcompa** [comment]
To reproduce:
```
conda create --name test python==3.8.13
conda activate test
pip install fractal-tasks-core
python -c 'import napari_workflows'
```
yielding
```python traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari_workflows/__init__.py", line 4, in <module>
    from ._workflow import Workflow
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari_workflows/_workflow.py", line 2, in <module>
    from napari import Viewer
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/_lazy.py", line 47, in __getattr__
    submod = import_module(f'{module_name}.{attr_to_modules[name]}')
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/components/__init__.py", line 24, in <module>
    from . import _viewer_key_bindings  # isort:skip
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/components/_viewer_key_bindings.py", line 9, in <module>
    from .viewer_model import ViewerModel
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/components/viewer_model.py", line 34, in <module>
    from ..plugins.utils import get_potential_readers, get_preferred_reader
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/plugins/__init__.py", line 10, in <module>
    from ._plugin_manager import NapariPluginManager
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/plugins/_plugin_manager.py", line 34, in <module>
    from . import _builtins, hook_specifications
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/plugins/_builtins.py", line 18, in <module>
    from ..utils.io import (
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/utils/io.py", line 27, in <module>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/napari/utils/io.py", line 27, in <setcomp>
    IMAGEIO_EXTENSIONS = {x for f in imageio.formats for x in f.extensions}
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/imageio/core/format.py", line 640, in <genexpr>
    return iter(x.format for x in self._formats)
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/imageio/config/plugins.py", line 85, in format
    module = importlib.import_module(self.module_name, self.package_name)
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tommaso/miniconda3/envs/fractal-fresh/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py", line 136, in <module>
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'
```

**Comment by jluethi** [comment]
It appears something changed in the imageio libary (imageio_ffmpeg needs to be installed separately) and napari doesn't handle that change gracefully. By adding `imageio_ffmpeg` to our dependencies (for the time being), we can avoid this issue.

**Comment by tcompa** [comment]
Ref: https://github.com/imageio/imageio/pull/880

I am now including this in poetry requirements, and then we can remove it once it is solved in napari.
