### ISSUE TITLE
[v1] Adapt manifest to fractal v1.x

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#160]
* Move it to specific file
* Conform to JSON schema

**Comment by tcompa** [comment]
Ref https://github.com/fractal-analytics-platform/fractal-server/pull/188

**Comment by tcompa** [comment]
@jacopo-exact
Could you provide an minimal example of `__FRACTAL_MANIFEST__.json`?

My guess was something like
```json
{
    "manifest_version": "1",
    "task_list": [
        {
            "name": "Create OME-ZARR structure",
            "executable": "/tmp/some/path",
            "input_type": "image",
            "output_type": "zarr",
            "default_args": {"num_levels": 2}
        }
    ]
}
```
but validating it via 
```python
with open("__FRACTAL_MANIFEST__.json", "r") as fin:
    manifest_dict = json.load(fin)
print(json.dumps(manifest_dict, indent=4))
manifest = ManifestV1(manifest_dict)
```
fails with
```python traceback
Traceback (most recent call last):
  File "validate_manifest.py", line 45, in <module>
    manifest = ManifestV1(manifest_dict)
  File "pydantic/main.py", line 333, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)
```

**Comment by tcompa** [comment]
My bad, I was missing the `meta` parameter.

@jacopo-exact, can we make it `Optional`?
