### ISSUE TITLE
Make cellpose task work with multiplexed processing

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#227]
When running cellpose on the multiplexing example 02, I get the following error:

```
2022-11-24 16:36:03,129; INFO; START cellpose_segmentation task
2022-11-24 16:36:03,131; INFO; /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples-v1/02_cardio_multiplexing/tmp_multiplexing_046-segmentation/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 489, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 89, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.4.6/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 183, in cellpose_segmentation
    raise Exception(f"ERROR: {labeling_channel} not in {chl_list}")
Exception: ERROR: A01_C01 not in {'0': ['A01_C01'], '1': ['A01_C01', 'A02_C03'], '2': ['A01_C01', 'A01_C02', 'A02_C03']}

```

Which makes sense, because we haven't figured out https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/211 yet to define channel references for multiplexing.

Eventually, cellpose should work in two modes:
1. Running over all cycles, i.e. pick A01_C01 per cycle: choosing by wavelength and parallelization level image
2. Running in a given cycle, e.g. either A01_C01 of acquisition 0 or 'DAPI_1' (if we go with unique channel names): choosing either by wavelength & acquisition or name and parallelization level well

**Comment by tcompa** [comment]
FYI, if we replace `value = metadata[key]` with the custom function `get_parameters_from_metadata`, as we do in `yokogawa_to_zarr`, then this task should probably work _as is_.

This doesn't change a thing about the broader discussion on how to address channels, but it's just for information.

**Comment by tcompa** [comment]
This is obsolete, as of #239

**Comment by tcompa** [comment]
(the discussion on multiplexing workflows continues on https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/230)
