### ISSUE TITLE
Multiplexing Parsing: Type annotation bug for metadata_tables

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#257]
The current type annotation for metadata_tables doesn't allow for dictionaries as input and that type annotation is enforced in Fractal. Will submit a PR for this as part of the work on tests & improvements to the multiplexing parsing from a table

Error:
```
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr_multiplex.py", line 469, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_ROOT/.fractal/fractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 87, in run_fractal_task
    task_args = TaskArgsModel(**pars)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TaskArguments
metadata_table
  str type expected (type=type_error.str)
```

**Comment by tcompa** [comment]
Closed with #258
