### ISSUE TITLE
napari 0.4.17 workarounds or drop dependency

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#259]
Currently, the newest napari release is making some issues. Some appear to be changes in napari, some may be the interactions with napari workflows or a given plugin. Reinforces the goal to be able to drop napari from the dependencies of the plugins. But while we still need napari, maybe it's easier to use napari 0.4.16 for the time being.

I'm documenting some issues and workarounds I found here.
1) Storing settings
Currently getting this error message upon napari workflow task start:
`PermissionError: [Errno 13] Permission denied: '/data/homes/USERNAME/.config/Napari/settings.yaml'`

Workaround found: Add `export XDG_CONFIG_HOME=${HOME}/.cache/XDG` to the WORKER_INIT

2) Getting this error when starting a napari workflow wrapper task:
```
/BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_tools_menu/__init__.py:6: UserWarning: importing napari._qt failed
  warnings.warn("importing napari._qt failed")
/BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_tools_menu/__init__.py:207: UserWarning: Error in monkey patching napari. Please let @haesleinleinhuepf know at
https://github.com/haesleinhuepf/napari-tools-menu/issues
  warnings.warn("Error in monkey patching napari. Please let @haesleinleinhuepf know at\nhttps://github.com/haesleinhuepf/napari-tools-menu/issues")
Traceback (most recent call last):
  File "/BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/fractal_tasks_core/napari_workflows_wrapper.py", line 604, in <module>
    run_fractal_task(
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 89, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/fractal_tasks_core/napari_workflows_wrapper.py", line 115, in napari_workflows_wrapper
    wf: napari_workflows.Worfklow = load_workflow(workflow_file)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_workflows/_io_yaml_v1.py", line 36, in load_workflow
    return unsafe_load(stream)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/__init__.py", line 145, in unsafe_load
    return load(stream, UnsafeLoader)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 523, in construct_python_tuple
    return tuple(self.construct_sequence(node))
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 570, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 719, in find_python_name
    return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_skimage_regionprops/__init__.py", line 1, in <module>
    from ._table import add_table, get_table, TableWidget
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_skimage_regionprops/_table.py", line 14, in <module>
    class TableWidget(QWidget):
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari_skimage_regionprops/_table.py", line 19, in TableWidget
    def __init__(self, layer: napari.layers.Layer, viewer:napari.Viewer = None):
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/_lazy.py", line 45, in __getattr__
    return import_module(f'{module_name}.{name}')
  File "/data/homes/fractal/.conda/envs/fractal-server-v1-b3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/layers/base/base.py", line 28, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/settings/__init__.py", line 5, in <module>
    from ._base import _NOT_SET
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/settings/_base.py", line 18, in <module>
    from ._yaml import PydanticYamlMixin
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/settings/_yaml.py", line 9, in <module>
    from ._fields import Version
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/settings/_fields.py", line 6, in <module>
    from ..utils.theme import available_themes
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/utils/theme.py", line 26, in <module>
    class Theme(EventedModel):
  File "//BASEPATHfractal-tasks-core0.6.2/venv/lib/python3.8/site-packages/napari/utils/theme.py", line 71, in Theme
    def _ensure_syntax_style(value: str) -> str:
  File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
  File "pydantic/class_validators.py", line 152, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "napari.utils.theme.Theme._ensure_syntax_style"; if this is intended, set `allow_reuse=True`
```

=> Not sure what triggers this. I'll be trying to downgrade our environment to napari 0.4.16 and retest in that.

**Comment by tcompa** [comment]
I'm now adding napari=0.4.16 as a dependency (note that it was not an explicit dependency until now, but it was required for other packages). This should fix things for now, and then let's make sure we can fully remove it as soon as possible.
