### ISSUE TITLE
`zarr.errors.ContainsGroupError` suddenly showing up in different workflows

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#275]
I'm running a few tests in parallel at FMI and suddenly, I keep getting `zarr.errors.ContainsGroupError` at different places of workflows. Normally, we'd get this error if we didn't delete an old output file. I made sure that it's in fresh files though.
Very weirdly, this error occurs for different parts. Currently at FMI, I can reproducibly get the 01 example to fail at the parsing step with an error like this:
```
anding/fractal/fractal-envs/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 279, in write_mapping
    g = f.create_group(k)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 853, in create_group
    return self._write_op(self._create_group_nosync, name, overwrite=overwrite)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 827, in _write_op
    return f(*args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 859, in _create_group_nosync
    init_group(self._store, path=path, chunk_store=self._chunk_store,
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 680, in _init_group_metadata
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path 'B/03/0/tables/well_ROI_table/varm' contains a group

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>
    run_fractal_task(
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 361, in create_ome_zarr
    write_elem(group_tables, "well_ROI_table", well_ROIs_table)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 221, in write_anndata
    write_elem(g, "varm", dict(adata.varm), dataset_kwargs=dataset_kwargs)
  File "/ENV/FOLDER/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
zarr.errors.ContainsGroupError: path "path 'B/03/0/tables/well_ROI_table/varm' contains a group\n\nAbove error raised while writing key 'varm' of <class 'zarr.hierarchy.Group'> to <zarr.storage.DirectoryStore object at 0x7fc539503df0>" contains a group
```

Sometimes this is varm part of the table, sometime this is var, sometimes obs.

And other workflows failed when building the cellpose pyramid with the same error. I don't currently understand what's happening here. Will try to reproduce this on the UZH side with example 01 next.

**Comment by jluethi** [comment]
I can also reproduce this error on the UZH side with example 01, here it also fails during cellpose pyramid building:

```
2022-12-15 15:29:40,611; INFO; [B_03_0] End cellpose_segmentation task for /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples-v1/01_cardio_tiny_dataset/tmp_workflow_test-4/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/, now building pyramids.
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 533, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 476, in cellpose_segmentation
    build_pyramid(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/lib_pyramid_creation.py", line 95, in build_pyramid
    previous_level = newlevel_rechunked.to_zarr(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/dask/array/core.py", line 2905, in to_zarr
    return to_zarr(self, *args, **kwargs)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/dask/array/core.py", line 3663, in to_zarr
    z = zarr.create(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/creation.py", line 169, in create
    init_array(store, shape=shape, chunks=chunks, dtype=dtype, compressor=compressor,
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 426, in init_array
    _init_array_metadata(store, shape=shape, chunks=chunks, dtype=dtype,
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 485, in _init_array_metadata
    raise ContainsArrayError(path)
zarr.errors.ContainsArrayError: path '1' contains an array
```

My first suspicion was an update in e.g. the Zarr library or the AnnData library. But neither have been updated recently. There were lots of changes to the poetry.lock today, but those aren't in the released version yet. Any ideas @tcompa ?

This is currently blocking all our tests and makes workflows fail at weird places. Haven't observed this before today though. I suspect it came with the 0.6.5 release somehow? Did something change in the dependencies that could be causing this?

**Comment by jluethi** [comment]
For reference, this was with server 1.0.0b5 and client 1.00a6. I'm testing with server 1.0.0b6 & b4 now to see if it makes a difference

**Comment by jluethi** [comment]
To make things even more confusing: While at FMI, I had my workflows result in a failed status with these errors in the logs, at UZH, the workflows actually appear to complete successfully. But the logs still contain those messages.

Thus, while those error tracebacks are worrying, maybe they are not the actual thing that made the workflow fail on the FMI setup. But we should certainly still figure out what causes them and fix that

**Comment by jluethi** [comment]
I take it back again. It also fails at UZH sometimes. I don't know why it runs through sometimes, but fails other times. I ran it another 3 times and all 3 runs of the 01 test failed. Two at the cellpose stage, one in the initial parsing

**Comment by tcompa** [comment]
For the record, example 01 in `fractal-demos` runs through locally (on my machine), when using the `process` backend. This is with versions server 1.0.0b6, client 1.0.0a6, tasks 0.6.5 (all on python 3.8).

Other (unrelated) info:
* In tasks 0.6.5 we switched from `napari-workflows` 0.2.3 to 0.2.8. This causes no obvious harm, but it can be checked explicitly.
* The tasks 0.6.4 release seems an innocent one (mostly creating the `tools` submodule).
* Some changes for the server from 1.0.0b2 to 1.0.0b4, for example, include:
    * Removing parsl
    * A bunch of related changes in poetry.lock, which don't look like they should really matter (to be verified)
    * The new job endpoint (irrelevant, I'd guess)
    * The capture of task errors
    * Refactor of env-variable names (this would be a typical gotcha, but I don't see an obvious connection with the current issue)
    * Customization of names for tasks input/output/error/slurm files

Nothing obvious comes to mind as a possible reason for the current issue - will dig further.

**Comment by jluethi** [comment]
> For the record, example 01 in fractal-demos runs through locally (on my machine), when using the process backend. This is with versions server 1.0.0b6, client 1.0.0a6, tasks 0.6.5 (all on python 3.8).

Does it run through consistently and without showing those errors in the log? For me, it runs through sometimes at the moment, but I always see some errors in the logs. And often, it fails either during the initial parsing or cellpose.

**Comment by jluethi** [comment]
I've been testing it with different server & tasks versions. Server 1.0.0b4, 1.0.0b5 & 1.0.0b6 with the 0.6.5 tasks all seem to have the same issues.

But the 0.6.4 fractal-tasks-core version does not appear to have this issue. I ran example 01 4x and it always completed successfully. Plus, it does not show any of those errors above in the logs

**Comment by tcompa** [comment]
> Does it run through consistently and without showing those errors in the log?
Yes. Ran it once, reinstalled everything, restarted the server, ran it twice. No errors in the logs, only warnings.

> For me, it runs through sometimes at the moment, but I always see some errors in the logs. And often, it fails either during the initial parsing or cellpose.

This difference on the `process` backend is unexpected.
Same exact package versions?
Which python version?
Fresh install in new envs?

**Comment by jluethi** [comment]
> Same exact package versions?
I've always run with client 1.0.0a6. Server side tested b4 to b6. Tasks always used 0.6.5, except in the last tests.

> Which python version?
Always Python 3.8.13

> Fresh install in new envs?
Yes, always fresh installs using the install scripts

> In tasks 0.6.5 we switched from napari-workflows 0.2.3 to 0.2.8. This causes no obvious harm, but it can be checked explicitly.

I guess that would be the main culprit to test now, since it appears like a 0.6.5 issue (but not always and potentially only on slurm? Would be super weird)

**Comment by jluethi** [comment]
To briefly summarize where we got to yesterday evening:
Using fractal-tasks-core 0.6.5 on the cluster (UZH or FMI), we are getting the errors above. 

The confusing part: Sometimes workflows run through, sometimes they fail during parsing, sometimes they fail during cellpose (I have not seen them fail in other places). In all those cases, some of these errors show up in the logs. Sometimes the first run of example 01 works, but subsequent runs fails.

This does not appear to be a problem when using the `process` executor to run things locally.

Using fractal-tasks-core 0.6.4 on the UZH cluster seems to avoid this problem (haven't had a chance to test this on the FMI setup yet).

**Comment by tcompa** [comment]
I can reproduce with tasks 0.6.5 (server 1.0.0b6 and client 1.0.0a6), already for a workflow with a single create-ome-zarr task. Switching to task 0.6.4 does not seem to solve the issue, I still get a `0.err` file like:
```python traceback
2022-12-16 07:48:24,387; INFO; START create_ome_zarr task
2022-12-16 07:48:24,573; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
2022-12-16 07:48:24,648; INFO; removing FOV overlaps for well='B03'
2022-12-16 07:48:25,282; INFO; END create_ome_zarr task
kmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>
    run_fractal_task(
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 89, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 287, in create_ome_zarr
    group_well = group_plate.create_group(f"{row}/{column}/")
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 853, in create_group
    return self._write_op(self._create_group_nosync, name, overwrite=overwrite)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 827, in _write_op
    return f(*args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 859, in _create_group_nosync
    init_group(self._store, path=path, chunk_store=self._chunk_store,
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.6.4/venv/lib/python3.8/site-packages/zarr/storage.py", line 680, in _init_group_metadata
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path 'B/03' contains a group
```

Notice that this file is probably written simultaneously by different parts of our code, since it has broken words (`kmanslab` instead of `pelkmanslab`).

**Comment by tcompa** [comment]
> I guess that would be the main culprit to test now, since it appears like a 0.6.5 issue (but not always and potentially only on slurm? Would be super weird)

> Using fractal-tasks-core 0.6.4 on the UZH cluster seems to avoid this problem (haven't had a chance to test this on the FMI setup yet).

I reproduced the error with 0.6.4.

**Comment by tcompa** [comment]
More info: removing `export XDG_CONFIG_HOME=${HOME}/.cache/XDG` from `WORKER_INIT` does not solve the issue.

**Comment by tcompa** [comment]
Logging some more of the ongoing debugging.

I created `examples-v1/275_debug`, with a minimal example that still fails as in this issue.

Notice that I created a "fake" tasks package (its wheel is in the `package` folder), where I removed quite a few dependencies. It's essentially the alpha1 version of tasks 0.6.6. This is meant to speed up the whole task-collection procedure (collection now takes <1 minute).

After running, I have the following `server/artifacts/workflow_000001_job_000001/0.err`:
```python traceback
/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/experimental/pytorch/_annloader.py:18: UserWarning: Сould not load pytorch.
  warnings.warn("Сould not load pytorch.")
2022-12-16 08:29:36,026; INFO; START create_ome_zarr task
2022-12-16 08:29:36,036; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
2022-12-16 08:29:36,336; INFO; removing FOV overlaps for well='B03'
/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/lib_remove_FOV_overlaps.py:309: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[well, :] = df_well.values
2022-12-16 08:29:37,226; INFO; END create_ome_zarr task
ractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 25, in wrapper
    g[k].attrs.setdefault("encoding-type", spec.encoding_type)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 457, in __getitem__
    raise KeyError(item)
KeyError: 'obsm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 396, in <module>
    run_fractal_task(
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 360, in create_ome_zarr
    write_elem(group_tables, "FOV_ROI_table", FOV_ROIs_table)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 220, in write_anndata
    write_elem(g, "obsm", dict(adata.obsm), dataset_kwargs=dataset_kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
KeyError: "'obsm'\n\nAbove error raised while writing key 'obsm' of <class 'zarr.hierarchy.Group'> to <zarr.storage.DirectoryStore object at 0x7f7bccb8bf40>"
fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 360, in create_ome_zarr
    write_elem(group_tables, "FOV_ROI_table", FOV_ROIs_table)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 218, in write_anndata
    write_elem(g, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/specs/methods.py", line 511, in write_dataframe
    write_elem(group, index_name, df.index._values, dataset_kwargs=dataset_kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
zarr.errors.ContainsArrayError: path "path 'B/03/0/tables/FOV_ROI_table/obs/FieldIndex' contains an array\n\nAbove error raised while writing key 'FieldIndex' of <class 'zarr.hierarchy.Group'> to <zarr.storage.DirectoryStore object at 0x7faf41c21f40>" contains an array
```

Also, unexpectedly, `server/artifacts/workflow_000001_job_000001/workflow.log` looks like
```python traceback
2022-12-16 08:29:23,462; INFO; fractal_server.__VERSION__: 1.0.0b6
2022-12-16 08:29:23,462; INFO; FRACTAL_RUNNER_BACKEND: slurm
2022-12-16 08:29:23,462; INFO; worker_init: None
2022-12-16 08:29:23,462; INFO; username: test01
2022-12-16 08:29:23,462; INFO; input_paths: [PosixPath('/data/homes/test01/fractal-demos/examples-v1/275_debug/../images/10.5281_zenodo.7059515/*.png')]
2022-12-16 08:29:23,462; INFO; output_path: /data/homes/test01/fractal-demos/examples-v1/275_debug/tmp_1/output/*.zarr
2022-12-16 08:29:23,462; INFO; input metadata: {}
2022-12-16 08:29:23,462; INFO; START workflow Workflow 1
2022-12-16 08:29:40,492; INFO; END workflow "Workflow 1"
```

**Comment by tcompa** [comment]
First relevant update: we could at least obtain a non-corrupt log file, by not sharing the `logger` between `create_ome_zarr.py` and `_utils.py` (that is, just using e.g. `logging.info` instead of some specific `logger.info`).

Now the `fractal task job-status` output says `status=failed`, and the `workflow.log` does not print the `END` log record.

**Comment by tcompa** [comment]
Since the error seems related to anndata, this info may be useful later
```
$ ./server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/bin/pip show anndata
Name: anndata
Version: 0.8.0
Summary: Annotated data.
Home-page: 
Author: Philipp Angerer, Alex Wolf, Isaac Virshup, Sergei Rybakov
Author-email: 
License: 
Location: /net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages
Requires: h5py, natsort, numpy, packaging, pandas, scipy
Required-by: fractal-tasks-core
```

**Comment by tcompa** [comment]
Another (currently not understood) observation.

The line
```
            group_well = group_plate.create_group(f"{row}/{column}/")
```
in the create-ome-zarr task is often related to this issue.
If we add a `raise ValueError("GOT HERE")` right after that line, we could observe logs like the one below. What is unclear is that the `ValueError` is correctly handled, and then there is an additional (corrupted) buffer of logs that is printed.

```python traceback
/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/anndata/experimental/pytorch/_annloader.py:18: UserWarning: Сould not load pytorch.
  warnings.warn("Сould not load pytorch.")

2022-12-16 09:33:21,596; INFO; START create_ome_zarr task
2022-12-16 09:33:21,597; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
2022-12-16 09:33:21,649; INFO; removing FOV overlaps for well='B03'
/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/lib_remove_FOV_overlaps.py:309: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[well, :] = df_well.values

2022-12-16 09:33:21,664; ERROR; GOT HERE
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 409, in <module>
    run_fractal_task(
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 110, in run_fractal_task
    raise e
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 107, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/fractal_tasks_core/create_ome_zarr.py", line 296, in create_ome_zarr
    raise ValueError("GOT HERE")
ValueError: GOT HERE

e_group(f"{row}/{column}/")
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 853, in create_group
    return self._write_op(self._create_group_nosync, name, overwrite=overwrite)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 827, in _write_op
    return f(*args, **kwargs)
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/hierarchy.py", line 859, in _create_group_nosync
    init_group(self._store, path=path, chunk_store=self._chunk_store,
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 633, in init_group
    _init_group_metadata(store=store, overwrite=overwrite, path=path,
  File "/data/homes/fractal/tommaso/fractal-demos/examples-v1/server/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_core0.6.5/venv/lib/python3.8/site-packages/zarr/storage.py", line 680, in _init_group_metadata
    raise ContainsGroupError(path)
zarr.errors.ContainsGroupError: path 'B/03' contains a group
```

**Comment by tcompa** [comment]
For the record, I thought https://github.com/fractal-analytics-platform/fractal-server/issues/361 was the reason for the corrupted log files, but my local fix was not sufficient to systematically get clean log files (that is, "without broken words").

Will keep digging.

**Comment by tcompa** [comment]
Yet another partial observation (many more will keep flowing here, I guess)

I confirm that putting a return statement (something like `return {"some": "metadata"}`) in the create-ome-zarr task, right before the block below leads to "successful" execution (i.e. the `0.err` logfile has nothing unexpected)

```python
        for row, column in well_rows_columns:
            group_well = group_plate.create_group(f"{row}/{column}/")

```

**Comment by tcompa** [comment]
Also:

I removed the two anndata-related lines (`write_elem(group_tables, "FOV_ROI_table", FOV_ROIs_table)` and `write_elem(group_tables, "well_ROI_table", well_ROIs_table)`) and the corresponding import, to make sure that the current issue is not related to anndata.
I confirm the issue is still present, thus pointing to a twofold issue:
1. "Something" goes wrong in the `group_well = group_plate.create_group(f"{row}/{column}/")` statement.
2. "Something" goes wrong because the exception is not raised correctly, and the err file is corrupted.

**Comment by tcompa** [comment]
Another hypothesis we are testing: cloudpickle and ExceptionProxy may be failing with non-standard python exceptions (e.g. the zarr one).

**Comment by tcompa** [comment]
> Another hypothesis we are testing: cloudpickle and ExceptionProxy may be failing with non-standard python exceptions (e.g. the zarr one).

We can confirm the issue is somewhere here.
Using server 1.0.0b3 (from github release) does **not** have the current issue.
