### ISSUE TITLE
Publish package on conda(-forge)?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#290]

**Comment by mfranzon** [comment]
## Create conda package
Few notes on how to create a conda package for fractal-tasks-core. 
#### - Install prerequisites 
 - ```conda install conda-build```
 - ```conda install conda-verify```

#### - Create yaml recipe
 - ```conda skeleton pypi fractal-tasks-core``` -> this creates a `/<package-name>/meta.yaml` file which contains the informations for the building process. 
 - the recipe requires some clean-up operations: 
 ```yaml
{% set name = "fractal-tasks-core" %}
{% set version = "0.7.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz" # this path is not correct
  sha256: c3dfe551320ff94b46121091f8946627d4cd17dc5cd8028f9a4b4e6882b2e1f2
```
It is necessary to remove that address and set the correct one taken from PyPi:
```yaml
url: "https://files.pythonhosted.org/packages/b4/1b/b37ffd8fa88e79a64dd16ebc626f919995bacf0182b259f30889bf417698/fractal_tasks_core-{{ version }}.tar.gz"
[conda_install_log.txt](https://github.com/fractal-analytics-platform/fractal-tasks-core/files/10794752/conda_install_log.txt)

```
Another constraint is related to [cellpose package](https://anaconda.org/conda-forge/cellpose/2.0.5/download/noarch/cellpose-2.0.5-pyhd8ed1ab_0.tar.bz2), which is not aligned with the pypi version, pypi=2.2 vs conda=2.0.5
Finally change ```torch``` in ```pytorch```. 

 - create a  `/<package-name>/conda_build_config.yaml`, in which you can specify the python versions that will be used to build you package.
```yaml
python:
    - 3.8
    - 3.9
    - 3.10
```

#### - Build the package
 - ```conda build .```, in the `/<package-name>/` directory

Then you can upload the package on your repository in [anaconda.org](https://anaconda.org/), or use the local version. 

## Results
We (@tcompa and me) noticed some problems during the installation phase. It fails in some cases but the error is not fully reproducible. On the machine used to build the package the installation works fine without problems (it takes ~15mins). We try to find a clear explanation about that but nothing meaningful arise at the moment. Here a full traceback of the installation error.
[conda_install_logs.txt](https://github.com/fractal-analytics-platform/fractal-tasks-core/files/10794761/conda_install_log.2.txt)

Last considerations about this results:
- One of the dependencies (cellpose) is not updated constantly on conda-forge as in PyPi, this could be potentially dangerous in terms of version mismatching that can be solved build, by ourself, the conda package for the latest version of cellpose
- Package installation requires a lot of time due to dependency tree. This is related to all the experimental software in the requirements.

**Comment by tcompa** [comment]
Thanks Marco!

Here is my higher-level view on this topic:

## Comments on the current status

The current packaging procedure is not yet satisfactory, because (1) it requires custom steps and (2) installation still fails on some machines for unclear reasons. If this process is not automated **and** reliable, then supporting an up-to-date conda package as well becomes a lot of work; we can of course take care of it, but it should be for a very good reason.

Something which would take a smaller effort is to say "we do not offer up-to-date conda packages, but from time to time (AKA when someone asks for it and we have time) we can prepare the build for _some_ version of fractal-tasks-core, which would still remain an experimental install (to be more explicit: if `conda install` fails on some machine, that wouldn't be our priority to fix it).

## More details

Re: cellpose
1. Nobody keeps the [conda cellpose package](https://anaconda.org/conda-forge/cellpose/files) up-to-date (the same could happen for another dependency, in the future). At the moment, their github/pypi/conda releases are all different.
2. We could have our own cellpose conda package and keep it up to date, but that adds quite some effort.
3. I think it's worth trying to ask the cellpose devs whether they plan on releasing on conda in a more regular way.
4. The workaround used by Marco this time is to use some older version of cellpose which is available on conda (2.0.5 instead of 2.2). This worked for this case, where we could live with 2.0.5, but it is obviously not a valid solution in general.

Re: other custom steps
1. We would need to replace torch with pytorch, to build on conda, but that's probably a minor issue.
2. I don't know why Marco had to replace the pypi address with the correct one. Hopefully this can be fixed in a clean way.

Re: failed install on some machines
1. We could not find a reason for the failure, at the moment.

## A possible alternative way

The procedure described by Marco is the one to publish directly on a [custom anaconda.org channel](https://anaconda.org/mfranzon/). The other option is to go [through conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html). The process is a bit more cumbersome (you have to open a [PR on a conda-forge repo](https://github.com/conda-forge/staged-recipes/pulls)), but then the build is somewhat automated and taken care of by conda-forge itself. This different approach _could_ lead to a more reliable package (that is, it could solve our installation problem on some machines), but we did not test it for the lack of time. Let's re-discuss the priority level of this issue before going too deep.

**Comment by tcompa** [comment]
@jluethi @gusqgm @ychiucco

Feel free to add one data point to the current small-ish sample, by running
```
conda install -c mfranzon -c conda-forge fractal-tasks-core -v
```
and reporting here the output (this should be done in an environment with python 3.9 or 3.10).

Note: it may take 15-20 minutes, both for success and failure.

**Comment by tcompa** [comment]
Just to report more explicitly about some discussion with @mfranzon. There are (at least) two different scenarios:
1. We do support regular conda releases, as we do for pypi, and we make them "as installable as possible". This is IMHO the preliminary requirement if we then want to use conda also inside fractal-server.
2. We release conda packages in a very irregular fashion, and with no special support. The intended use case, IMHO, is for those who want to try/use our tasks from outside Fractal.

**Comment by tcompa** [comment]
Closing for now, as of our latest common discussion (yesterday). The effort is not (currently) justified.
Let's come back to this issue as a starting point for when there will be more compelling reasons for investing on conda.

**Comment by tcompa** [comment]
(but reports about the output of `conda install` are still appreciated, for the record)

**Comment by jluethi** [comment]
I tried the conda install today and can't find the fractal-tasks-core package for arm macs using my local setup. I get this stack trace:

```
(fractal-conda-test) joel@f210m-368c27 ~ » conda install -c mfranzon -c conda-forge fractal-tasks-core -v
Collecting package metadata (current_repodata.json): ...working... INFO conda.core.subdir_data:fetch_repodata_remote_request(625): Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/mfranzon/osx-arm64/current_repodata.json
done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Traceback (most recent call last):
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 136, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 179, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 297, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/core/solve.py", line 591, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/resolve.py", line 557, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
    return f(*args, **kwds)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/resolve.py", line 578, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/resolve.py", line 290, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - fractal-tasks-core

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1118, in __call__
    return func(*args, **kwargs)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
    exit_code = do_call(args, p)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/Users/joel/mambaforge/lib/python3.10/site-packages/conda/cli/install.py", line 289, in install
    raise PackagesNotFoundError(e._formatted_chains, channels_urls)
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - fractal-tasks-core

Current channels:

  - https://conda.anaconda.org/mfranzon/osx-arm64
  - https://conda.anaconda.org/mfranzon/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

If further investigation is needed, let me know. Otherwise, this is just for the record when we get back to that.

**Comment by tcompa** [comment]
Oh, right, that makes sense.
I think that Marco only build the package for linux-64, and not for osx.

**Comment by jluethi** [comment]
Makes sense. I'll give it a go from the Pelkmans lab cluster to see how that goes for me :)

**Comment by jluethi** [comment]
I'm trying to install it on Linux, but it's been at `Solving environment: ...working... ` for 2h now. Something is clearly going wrong with the environment solution, I have never seen this in other conda packages. 

Full log so far:
```
(fractal-conda-test) jluethi@pelkmanslab-slurm-master-001:~$ conda install -c mfranzon -c conda-forge fractal-tasks-core -v
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/mfranzon/linux-64/current_repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
```

**Comment by aangelone2** [comment]
*Before you comment*: I am re-running this build process again (I had to update `conda` in the middle of the process, which may have skewed the build). I will update this edit with a cleaner build and more logs).

I am working on the construction of a conda-compatible package, posting here the steps I performed.

# Building a conda build environment

```
$ conda create -n fractal-tasks-core-build-env conda-build git
$ conda activate fractal-tasks-core-build-env
```

# Installing grayskull for recipe file

`conda skeleton` has multiple reported issues for packages lacking a `setup.py` file (such as `fractal-tasks-core`). We use the community alternative `grayskull` here.

```
$ conda install -c conda-forge grayskull
$ grayskull pypi fractal-tasks-core=0.10.1
```

The generated `fractal-tasks-core/meta.yaml` file looks like

```
{% set name = "fractal-tasks-core" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractal_tasks_core-{{ version }}.tar.gz
  sha256: 4ceb499d9ab18058eacf74b43e2e4b30e0f8851bf668475a0fcbda573ca6d321

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - dask-core >=2023.1.0
    - zarr >=2.13.6,<3
    - numpy <2
    - pandas >=1.2.0,<2
    - defusedxml >=0.7.1,<0.8.0
    - lxml >=4.9.1,<5.0.0
    - pydantic <2
    - docstring_parser >=0.15.0,<0.16.0
    - anndata >=0.8.0,<=0.9.1
  run_constrained:
    - Pillow >=9.1.1,<10.0.0
    - imageio-ffmpeg >=0.4.7,<0.5.0
    - scikit-image >=0.19
    - napari-segment-blobs-and-things-with-membranes >=0.3.3,<0.4.0
    - napari-workflows >=0.2.8,<0.3.0
    - napari-skimage-regionprops >=0.8.1,<0.9.0
    - napari-tools-menu >=0.1.19,<0.2.0
    - cellpose >=2.2.0,<2.3.0
    - pytorch <=2.0.0

test:
  imports:
    - fractal_tasks_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fractal-analytics-platform/fractal-tasks-core
  summary: ''
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aangelone2
```

# Generating the package files

```
$ conda build -c conda-forge fractal-tasks-core
```

The generated `tar.bz2` file resides in the `${CONDA_PREFIX}/conda-bld/noarch/` directory.

Clipped package list from output:

```
_libgcc_mutex:      0.1-conda_forge               conda-forge
_openmp_mutex:      4.5-2_gnu                     conda-forge
anndata:            0.9.1-pyhd8ed1ab_0            conda-forge
asciitree:          0.3.3-py_2                    conda-forge
brotli-python:      1.1.0-py311hb755f60_0         conda-forge
bzip2:              1.0.8-h7f98852_4              conda-forge
c-ares:             1.19.1-hd590300_0             conda-forge
ca-certificates:    2023.7.22-hbcca054_0          conda-forge
cached-property:    1.5.2-hd8ed1ab_1              conda-forge
cached_property:    1.5.2-pyha770c72_1            conda-forge
certifi:            2023.7.22-pyhd8ed1ab_0        conda-forge
charset-normalizer: 3.2.0-pyhd8ed1ab_0            conda-forge
click:              8.1.7-unix_pyh707e725_0       conda-forge
cloudpickle:        2.2.1-pyhd8ed1ab_0            conda-forge
dask-core:          2023.9.0-pyhd8ed1ab_0         conda-forge
defusedxml:         0.7.1-pyhd8ed1ab_0            conda-forge
docstring_parser:   0.15-pyhd8ed1ab_0             conda-forge
entrypoints:        0.4-pyhd8ed1ab_0              conda-forge
fasteners:          0.17.3-pyhd8ed1ab_0           conda-forge
fractal-tasks-core: 0.10.1-py_0                   local      
fsspec:             2023.9.0-pyh1a96a4e_0         conda-forge
h5py:               3.9.0-nompi_py311h3839ddf_102 conda-forge
hdf5:               1.14.2-nompi_h4f84152_100     conda-forge
icu:                73.2-h59595ed_0               conda-forge
idna:               3.4-pyhd8ed1ab_0              conda-forge
importlib-metadata: 6.8.0-pyha770c72_0            conda-forge
importlib_metadata: 6.8.0-hd8ed1ab_0              conda-forge
keyutils:           1.6.1-h166bdaf_0              conda-forge
krb5:               1.21.2-h659d440_0             conda-forge
ld_impl_linux-64:   2.40-h41732ed_0               conda-forge
libaec:             1.0.6-hcb278e6_1              conda-forge
libblas:            3.9.0-18_linux64_openblas     conda-forge
libcblas:           3.9.0-18_linux64_openblas     conda-forge
libcurl:            8.2.1-hca28451_0              conda-forge
libedit:            3.1.20191231-he28a2e2_2       conda-forge
libev:              4.33-h516909a_1               conda-forge
libexpat:           2.5.0-hcb278e6_1              conda-forge
libffi:             3.4.2-h7f98852_5              conda-forge
libgcc-ng:          13.1.0-he5830b7_0             conda-forge
libgfortran-ng:     13.1.0-h69a702a_0             conda-forge
libgfortran5:       13.1.0-h15d22d2_0             conda-forge
libgomp:            13.1.0-he5830b7_0             conda-forge
libiconv:           1.17-h166bdaf_0               conda-forge
liblapack:          3.9.0-18_linux64_openblas     conda-forge
libnghttp2:         1.52.0-h61bc06f_0             conda-forge
libnsl:             2.0.0-h7f98852_0              conda-forge
libopenblas:        0.3.24-pthreads_h413a1c8_0    conda-forge
libsqlite:          3.43.0-h2797004_0             conda-forge
libssh2:            1.11.0-h0841786_0             conda-forge
libstdcxx-ng:       13.1.0-hfd8a6a1_0             conda-forge
libuuid:            2.38.1-h0b41bf4_0             conda-forge
libxml2:            2.11.5-h232c23b_1             conda-forge
libxslt:            1.1.37-h0054252_1             conda-forge
libzlib:            1.2.13-hd590300_5             conda-forge
locket:             1.0.0-pyhd8ed1ab_0            conda-forge
lxml:               4.9.3-py311h1a07684_0         conda-forge
msgpack-python:     1.0.5-py311ha3edf6b_0         conda-forge
natsort:            8.4.0-pyhd8ed1ab_0            conda-forge
ncurses:            6.4-hcb278e6_0                conda-forge
numcodecs:          0.11.0-py311hcafe171_1        conda-forge
numpy:              1.25.2-py311h64a7726_0        conda-forge
openssl:            3.1.2-hd590300_0              conda-forge
packaging:          23.1-pyhd8ed1ab_0             conda-forge
pandas:             1.5.3-py311h2872171_1         conda-forge
partd:              1.4.0-pyhd8ed1ab_0            conda-forge
pip:                23.2.1-pyhd8ed1ab_0           conda-forge
platformdirs:       3.10.0-pyhd8ed1ab_0           conda-forge
pooch:              1.7.0-pyha770c72_3            conda-forge
pydantic:           1.10.12-py311h459d7ec_1       conda-forge
pysocks:            1.7.1-pyha2e5f31_6            conda-forge
python:             3.11.5-hab00c5b_0_cpython     conda-forge
python-dateutil:    2.8.2-pyhd8ed1ab_0            conda-forge
python_abi:         3.11-3_cp311                  conda-forge
pytz:               2023.3.post1-pyhd8ed1ab_0     conda-forge
pyyaml:             6.0.1-py311h459d7ec_0         conda-forge
readline:           8.2-h8228510_1                conda-forge
requests:           2.31.0-pyhd8ed1ab_0           conda-forge
scipy:              1.11.2-py311h64a7726_0        conda-forge
setuptools:         68.1.2-pyhd8ed1ab_0           conda-forge
six:                1.16.0-pyh6c4a22f_0           conda-forge
tk:                 8.6.12-h27826a3_0             conda-forge
toolz:              0.12.0-pyhd8ed1ab_0           conda-forge
typing-extensions:  4.7.1-hd8ed1ab_0              conda-forge
typing_extensions:  4.7.1-pyha770c72_0            conda-forge
tzdata:             2023c-h71feb2d_0              conda-forge
urllib3:            2.0.4-pyhd8ed1ab_0            conda-forge
wheel:              0.41.2-pyhd8ed1ab_0           conda-forge
xz:                 5.2.6-h166bdaf_0              conda-forge
yaml:               0.2.5-h7f98852_2              conda-forge
zarr:               2.16.1-pyhd8ed1ab_0           conda-forge
zipp:               3.16.2-pyhd8ed1ab_0           conda-forge
zstd:               1.5.5-hfc55251_0              conda-forge
```

(notice the `1.10.12` version of `pydantic`, available on `conda-forge`).

# Installing the package from local files

```
$ conda install -c conda-forge -c file://${CONDA_PREFIX}/conda-bld/noarch/ fractal-tasks-core
```

# Testing

```
python -c "from fractal_tasks_core.tasks.create_ome_zarr import create_ome_zarr"
```

results in the error

```
2023-09-06 09:27:10,811; INFO; NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nemesis4/.miniconda/envs/fractal-tasks-core-build/lib/python3.11/site-packages/fractal_tasks_core/tasks/create_ome_zarr.py", line 23, in <module>
    from pydantic.decorator import validate_arguments
ModuleNotFoundError: No module named 'pydantic.decorator'
```

# Troubleshooting

The installed package list is

```
conda list
```

```
# packages in environment at /home/.../.miniconda/envs/fractal-tasks-core-build:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
anndata                   0.9.1              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
beautifulsoup4            4.12.2          py311h06a4308_0  
blas                      1.0                         mkl  
boltons                   23.0.0          py311h06a4308_0  
bottleneck                1.3.5           py311hbed6279_0  
brotlipy                  0.7.0           py311h5eee18b_1002  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h5eee18b_3  
chardet                   4.0.0           py311h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py311h06a4308_0  
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.7.3          py311h06a4308_0  
conda-build               3.26.1          py311h06a4308_0  
conda-index               0.2.3           py311h06a4308_0  
conda-package-handling    2.2.0           py311h06a4308_0  
conda-package-streaming   0.9.0           py311h06a4308_0  
conda-souschef            2.2.3              pyhd8ed1ab_0    conda-forge
cryptography              41.0.2          py311h22a60cf_0  
curl                      8.2.1                hdbd6064_0  
dask-core                 2023.9.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h6a678d5_0  
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
filelock                  3.9.0           py311h06a4308_0  
fractal-tasks-core        0.10.1                     py_0    file:///home/nemesis4/.miniconda/envs/fractal-tasks-core-build/conda-bld
fsspec                    2023.9.0           pyh1a96a4e_0    conda-forge
gdbm                      1.18                 hd4cb3f1_4  
gettext                   0.21.0               h39681ba_1  
git                       2.40.1          pl5340h36fbf9e_1  
glob2                     0.7                pyhd3eb1b0_0  
grayskull                 2.3.1              pyhd8ed1ab_0    conda-forge
h5py                      3.9.0           py311hdd6beaf_0  
hdf5                      1.12.1               h2b7332f_3  
icu                       73.1                 h6a678d5_0  
idna                      3.4             py311h06a4308_0  
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46305  
jinja2                    3.1.2           py311h06a4308_0  
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
krb5                      1.20.1               h143b758_1  
ld_impl_linux-64          2.38                 h1181459_1  
libarchive                3.6.2                h6ac8c49_2  
libcurl                   8.2.1                h251f7ec_0  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   11.2.0               h1234567_1  
liblief                   0.12.3               h6a678d5_0  
libnghttp2                1.52.0               h2d74bed_1  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxml2                   2.10.4               hf1b16e4_1  
libxslt                   1.1.37               h5eee18b_1  
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.2           py311h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.1           py311h5eee18b_0  
mkl                       2023.1.0         h213fc3f_46343  
mkl-service               2.4.0           py311h5eee18b_1  
mkl_fft                   1.3.6           py311ha02d727_1  
mkl_random                1.2.2           py311ha02d727_1  
more-itertools            8.12.0             pyhd3eb1b0_0  
msgpack-python            1.0.3           py311hdb19cb5_0  
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
numcodecs                 0.11.0          py311h6a678d5_0  
numexpr                   2.8.4           py311h65dcdc2_1  
numpy                     1.25.2          py311h08b1b3b_0  
numpy-base                1.25.2          py311hf175353_0  
openssl                   3.0.10               h7f8727e_2  
packaging                 23.1            py311h06a4308_0  
pandas                    1.5.3           py311hba01205_0  
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             h7b6447c_1001  
patchelf                  0.17.2               h6a678d5_0  
pcre2                     10.42                hebb0a14_0  
perl                      5.34.0               h5eee18b_2  
pip                       23.2.1          py311h06a4308_0  
pkginfo                   1.9.6           py311h06a4308_0  
pluggy                    1.0.0           py311h06a4308_1  
progressbar2              4.2.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.0           py311h5eee18b_0  
py-lief                   0.12.3          py311h6a678d5_0  
pycosat                   0.6.4           py311h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  0.18.2                     py_0    conda-forge
pyopenssl                 23.2.0          py311h06a4308_0  
pysocks                   1.7.1           py311h06a4308_0  
python                    3.11.4               h955ad1f_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-utils              3.7.0              pyhd8ed1ab_1    conda-forge
pytz                      2022.7          py311h06a4308_0  
pyyaml                    6.0             py311h5eee18b_1  
rapidfuzz                 2.13.7          py311ha02d727_0  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0          py311h06a4308_0  
ruamel.yaml               0.17.21         py311h5eee18b_0  
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
scipy                     1.11.1          py311h08b1b3b_0  
semver                    3.0.1              pyhd8ed1ab_0    conda-forge
setuptools                68.0.0          py311h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.4             py311h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
stdlib-list               0.8.0              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0          py311h06a4308_0  
tqdm                      4.65.0          py311h92b7b1e_0  
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16         py311h06a4308_0  
wheel                     0.38.4          py311h06a4308_0  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
zarr                      2.16.1             pyhd8ed1ab_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0          py311h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

Notice the much lower version of `pydantic` (`0.18.2`) than the one available on `conda-forge` and displayed when building the package.

I solved this (roughly) by running

```
conda upgrade --all
```

twice; both times packages were updated, the second time including `pydantic` to `1.10.8`, which solved the issue.

**Comment by tcompa** [comment]
Brief comments:

1. We can also choose to specify the architecture. We start with linux-64, and then we repeat the whole process for other relevant architectures.

2. It's true that there is no up-to-date pydantic v1 `noarch` package on https://anaconda.org/conda-forge/pydantic/files?sort=basename&sort_order=asc&page=14, but we obviously need a recent version.
![Screenshot from 2023-09-06 11-50-07](https://github.com/fractal-analytics-platform/fractal-tasks-core/assets/3862206/6223ec22-9db5-46f4-a110-7d2918c630c1)

3. What about package extras? There is one (named `fractal-tasks`) which I think you are not including, right? That extra includes "heavy" dependencies (e.g. torch), and it could create issues.

**Comment by aangelone2** [comment]
Update on the previous procedure. In order to specify the platform (or at least to lock the repository from which data is taken to be the `linux-64` one) I tried the following, which all failed:

- Modifying `meta.yaml` by setting `pydantic >=1, <2`, in order to force `conda install` to go for the newer version (does not work, still downloads the version from `noarch`).
- Calling `conda convert <tar.bz2 file> -p linux-64 -o linux/` on the generated archive (`conda convert` fails with an undocumented error).
- Trying to set `conda-forge` as a lower-priority channel than the default for `conda build/install`, by adding it manually with `conda --prepend` (no changes).
- Trying to pass `conda-forge/linux-64` as channel when running `conda build/install` (no changes).
- Removing `conda-forge` from the build process (build process fails - `conda-forge` is necessary for a few dependencies).

Slightly more successful, but still a failure:

- Removing the `noarch: python` line from the `meta.yaml` file. This caused the package to appear in the `${CONDA_PREFIX}/conda-bld/linux-64` folder, but the package still builds by seeking dependencies in the `noarch` repository.
