### ISSUE TITLE
Mismatch between FOV ROI table and image list, if selecting only a subset of Z planes

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#331]
Does image parsing work for a single Z plane? I think the answer is no, at the moment. To be checked.

---

The logs of an experimental test, where I only left the Z01 images, are
```python traceback
2023-03-01 12:32:19,892; INFO; [glob_with_multiple_patterns] patterns=['*.png']
2023-03-01 12:32:19,892; INFO; [glob_with_multiple_patterns] Found 3 items
2023-03-01 12:32:19,892; WARNING; Skipping "1231231231231_asdasd.png". Original error: 1231231231231_asdasd not valid
2023-03-01 12:32:19,892; INFO; Creating 20200812-CardiomyocyteDifferentiation14-Cycle1.zarr
2023-03-01 12:32:19,925; INFO; removing FOV overlaps for well='B03'
2023-03-01 12:32:19,927; INFO; [glob_with_multiple_patterns] patterns=['20200812-CardiomyocyteDifferentiation14-Cycle1_*.png']
2023-03-01 12:32:19,927; INFO; [glob_with_multiple_patterns] Found 2 items
2023-03-01 12:32:19,928; INFO; [glob_with_multiple_patterns] patterns=['20200812-CardiomyocyteDifferentiation14-Cycle1_B03*.png']
2023-03-01 12:32:19,928; INFO; [glob_with_multiple_patterns] Found 2 items
run_workflow.py:72 <module>
    metadata: {
        'plate': [
            '20200812-CardiomyocyteDifferentiation14-Cycle1.zarr',
        ],
        'well': [
            '20200812-CardiomyocyteDifferentiation14-Cycle1.zarr/B/03/',
        ],
        'image': [
            '20200812-CardiomyocyteDifferentiation14-Cycle1.zarr/B/03/0/',
        ],
        'num_levels': 2,
        'coarsening_xy': 2,
        'image_extension': 'png',
        'image_glob_patterns': None,
        'original_paths': [
            '10.5281_zenodo.7059515/',
        ],
    } (dict) len=8
2023-03-01 12:32:19,989; INFO; [glob_with_multiple_patterns] patterns=['*_B03_*.png']
2023-03-01 12:32:19,989; INFO; [glob_with_multiple_patterns] Found 2 items
2023-03-01 12:32:20,071; INFO; [glob_with_multiple_patterns] patterns=['*_B03_*A01*C01*.png']
2023-03-01 12:32:20,072; INFO; [glob_with_multiple_patterns] Found 2 items
Traceback (most recent call last):
  File "/home/tommaso/Fractal/fractal-tasks-core/examples/01_cardio_tiny_dataset_single_Z_plane/run_workflow.py", line 76, in <module>
    yokogawa_to_ome_zarr(
  File "/home/tommaso/Fractal/fractal-tasks-core/fractal_tasks_core/yokogawa_to_ome_zarr.py", line 187, in yokogawa_to_ome_zarr
    FOV_3D = da.concatenate(
  File "/home/tommaso/.cache/pypoetry/virtualenvs/fractal-tasks-core-UoMDyr20-py3.10/lib/python3.10/site-packages/dask/array/core.py", line 4225, in concatenate
    raise ValueError("Need array(s) to concatenate")
ValueError: Need array(s) to concatenate
```

**Comment by tcompa** [comment]
The error comes from the mismatch from the FOV ROI table.

If there are 2 images per Z plane, and 2 Z planes, the FOV ROI table includes two ROIs of two Z planes each.
If we remove some images (those for Z=2) from the image folder, without updating the ROI table, then yokogawa_to_zarr will expect 4 images and it will fail when it finds only 2.
