### ISSUE TITLE
Specifying model_type in cellpose currently leads to task error

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#343]
Changing "model_type" leads to an error downloading the model, but it can use the default model without issues.

I'm running example 01 and wanted to change the cellpose model_type from the default "cyto2" to "nuclei".

For some reason, setting the `"model_type": "nuclei"` (in the parameters) leads to this workflow to fail during the cellpose task with the following error:
```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-i57dgcrc because the default path (/data/homes/fractal/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-03-08 14:25:29,418; INFO; START cellpose_segmentation task
2023-03-08 14:25:29,419; INFO; /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_nuclei/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/
2023-03-08 14:25:29,461; INFO; [B_03_0] data_zyx.shape=(1, 540, 1280)
2023-03-08 14:25:29,512; INFO; new_labels=['nuclei']
2023-03-08 14:25:29,512; INFO; existing_labels=[]
2023-03-08 14:25:29,523; INFO; [B_03_0] /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_nuclei/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/labels/nuclei/0
2023-03-08 14:25:29,529; INFO; [B_03_0] mask will have shape (1, 540, 1280) and chunks ((1,), (540,), (1280,))
2023-03-08 14:25:29,531; INFO; TORCH CUDA version not installed/working.
2023-03-08 14:25:29,532; INFO; >> nuclei << model set to be used
2023-03-08 14:25:29,532; INFO; Downloading: "https://www.cellpose.org/models/ModelInCellposeZoo.nucleitorch_0" to /data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH/ModelInCellposeZoo.nucleitorch_0

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 642, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/_utils.py", line 91, in run_fractal_task
    metadata_update = task_function(**task_args.dict(exclude_unset=True))
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 460, in cellpose_segmentation
    model = models.CellposeModel(gpu=gpu, model_type=model_type)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in __init__
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 346, in <listcomp>
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 30, in model_path
    return cache_model_path(basename)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/models.py", line 43, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/cellpose/utils.py", line 64, in download_url_to_file
    u = urlopen(url)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/homes/fractal/anaconda3/envs/fractal-server-1.1.0a1/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

If I specify the model to be used as "cyto2", it also fails with the same error => it's not about a specific model, but whenever one

Here's the relevant traceback:
```
2023-03-08 14:57:21,268; INFO; >> cyto2 << model set to be used
2023-03-08 14:57:21,269; INFO; Downloading: "https://www.cellpose.org/models/ModelInCellposeZoo.cyto2torch_0" to /data/homes/jluethi/.cache/CELLPOSE_LOCAL_MODELS_PATH/ModelInCellposeZoo.cyto2torch_0

Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR_110a1/.fractal/fractal-tasks-core0.8.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 642, in <module>
    run_fractal_task(
```

This was all with `export CELLPOSE_LOCAL_MODELS_PATH=${HOME}/.cache/CELLPOSE_LOCAL_MODELS_PATH` in the WORKER_INIT.

It runs through if I don't specify the model to be used (=> defaults to cyto2). The relevant log is this:
```
2023-03-08 15:01:01,126; INFO; TORCH CUDA version not installed/working.
2023-03-08 15:01:01,126; INFO; >> cyto2 << model set to be used
2023-03-08 15:01:01,127; INFO; >>>> using CPU
2023-03-08 15:01:02,360; INFO; >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-03-08 15:01:02,360; INFO; [B_03_0] Start cellpose_segmentation task for /net/nfs4/pelkmanslab-fileserver-jluethi/data/homes/jluethi/v1_fractal/fractal-demos/examples/01_cardio_tiny_dataset/tmp_cp_defaultModel/output/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0/
```

Doing the relevant part of the code manually in a conda env with cellpose on the cluster does not reproduce this error (i.e. running the following):
```
from cellpose import models
model_select = 'nuclei'
use_GPU = False
model = models.CellposeModel(gpu=use_GPU, model_type=model_select)
```

**Comment by tcompa** [comment]
The path https://www.cellpose.org/models/ModelInCellposeZoo.nucleitorch_0 clearly does not exist (`ModelInCellposeZoo` is our own class). I'll check this out.

**Comment by tcompa** [comment]
It's a problem with `Enum` (my bad).

This block
```
from cellpose import models
from enum import Enum

ModelInCellposeZoo = Enum(
    "ModelInCellposeZoo",
    ((value, value) for value in models.MODEL_NAMES),
    type=str,
)


print(ModelInCellposeZoo("nuclei"))
```
prints `ModelInCellposeZoo.nuclei` instead of the expected `nuclei` string.

**Comment by tcompa** [comment]
For the record, the following block would work as expected - but only starting from python 3.11

```python
from enum import StrEnum

MODEL_NAMES = ["nuclei", "else"]

ModelInCellposeZoo = StrEnum(
    "ModelInCellposeZoo",
    ((value, value) for value in MODEL_NAMES),
)

print(ModelInCellposeZoo("nuclei"))
```

**Comment by tcompa** [comment]
Also note that this error does not appear in the CI, since we mostly run examples as python functions (thus skipping pydnatic argument validation).

**Comment by jluethi** [comment]
Thanks Tommaso! I like the PR as a temporary fix and would be in favor of a 0.8.1 release with this :)

And then we can figure out how to do this cleanly to already validate correctly via pydantic. Useful longer term

**Comment by tcompa** [comment]
Bugfix released in 0.8.1

**Comment by jluethi** [comment]
Thanks Tommaso! 🎉
