### ISSUE TITLE
Cellpose task fails when `output_ROI_table` != None, but no objects were found

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#354]
While working with @silvbarb, we ran into the following issue:
If one runs the cellpose task and activates the saving of an output ROI table (by setting `output_ROI_table` to something different from None) in a well where Cellpose doesn't find any label objects (e.g. we ran on subsets on just one FOV), then the whole task fails.

The desired behavior would be to just get an empty ROI table.

Here's the traceback from it:
```
Traceback (most recent call last):
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 693, in <module>
    run_fractal_task(
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/fractal_tasks_core/_utils.py", line 91, in run_fractal_task
    metadata_update = task_function(**task_args.dict(exclude_unset=True))
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/fractal_tasks_core/cellpose_segmentation.py", line 571, in cellpose_segmentation
    bbox_df = array_to_bounding_box_table(
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/fractal_tasks_core/lib_regions_of_interest.py", line 342, in array_to_bounding_box_table
    df = pd.DataFrame(np.array(elem_list), columns=df_columns)
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 722, in __init__
    mgr = ndarray_to_mgr(
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 349, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/VENV/FOLDER/.fractal/fractal-tasks-core0.9.0/venv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 416, in _check_values_indices_shape_match
    raise ValueError("Empty data passed with indices specified.")
ValueError: Empty data passed with indices specified.
```

**Comment by tcompa** [comment]
Quick questions:
- Any specific reason for writing an empty table to disk, rather than not writing anything?
- Should we support looping over empty ROI tables, in general? I think this currently would break the ROI-table-to-indices conversion function (or at least it's not an expected scenario), but we should include an additional if/else check if we start having some empty tables lying around.

**Comment by jluethi** [comment]
> Any specific reason for writing an empty table to disk, rather than not writing anything?

Especially in larger plates, we may have scenarios where 99% of wells have objects that are segmented, but one well does not. In that case, would be great if all the logic downstream works the same for that well, i.e. one can save the ROI tables (even if some wells may not have content), one can run further segmentation based on those ROI tables and one can run measurements on those ROI tables.

I see 2 ways of achieving that:
1) Write empty tables and have the downstream processing be able to deal with an empty table
2) Make tasks not fail when no objects are present. Don't write a table. But then have downstream tasks deal with the absence of a table without failing.

1) seems more intuitive to me (i.e. I can loop over an empty list => not do anything. But I can't loop over a list that doesn't exist). But we can also discuss going more the route of 2)
