### ISSUE TITLE
Napari error (GL_MAX_TEXTURE_SIZE exceeded) when loading plate with missing wells

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#51]
We start from a zarr file with two wells (B07 and B011), with plate .zattrs:
```
"plate": {
         "acquisitions": [{"id": 0, "name": "210305NAR005AAN"}],
         "columns": [
                 {"name": "07"},
                 {"name": "11"}
                 ],
         "rows": [
                 {"name": "B"}
                 ],
         "wells": [
                 {"path": "B/07"},
                 {"path": "B/11"}
                 ]
}}
```
and napari shows the two wells next to each other (which is wrong), but it does not complain about (lazily) loading a highest-resolution level which has shape (4, 1, 8640, 25600).

Now we add more (missing) columns, since we want napari to show the two wells in their correct position.
```
{"plate": {
         "acquisitions": [{"id": 0, "name": "210305NAR005AAN"}],
         "columns": [
                 {"name": "07"},
                 {"name": "08"},
                 {"name": "09"},
                 {"name": "10"},
                 {"name": "11"}
                 ],
         "rows": [
                 {"name": "B"}
                 ],
         "wells": [
                 {"path": "B/07"},
                 {"path": "B/11"}
                 ]
}}
```
This results in an error, with the last part of napari's log reading:
```
WARNING: Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 1025, in on_draw
    layer._update_draw(
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/layers/base/base.py", line 1593, in _update_draw
    self.refresh()
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/layers/base/base.py", line 1179, in refresh
    self.events.set_data()  # refresh is called in _update_dims which means that extent cache is invalidated. Then, base on this event extent cache in layerlist is invalidated.
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 783, in _invoke_callback
    cb()
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 112, in _on_data_change
    self._set_node_data(self.node, self.layer._data_view)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 124, in _set_node_data
    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 222, in downsample_texture
    raise ValueError(
ValueError: Shape of in dividual tiles in multiscale (2880, 21330) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.
12:14:36 WARNING Traceback (most recent call last):
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 1025, in on_draw
    layer._update_draw(
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/layers/base/base.py", line 1593, in _update_draw
    self.refresh()
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/layers/base/base.py", line 1179, in refresh
    self.events.set_data()  # refresh is called in _update_dims which means that extent cache is invalidated. Then, base on this event extent cache in layerlist is invalidated.
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/utils/events/event.py", line 783, in _invoke_callback
    cb()
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 112, in _on_data_change
    self._set_node_data(self.node, self.layer._data_view)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 124, in _set_node_data
    data = self.downsample_texture(data, self.MAX_TEXTURE_SIZE_2D)
  File "/home/tommaso/miniconda3/envs/fractal/lib/python3.8/site-packages/napari/_vispy/layers/image.py", line 222, in downsample_texture
    raise ValueError(
ValueError: Shape of in dividual tiles in multiscale (2880, 21330) cannot exceed GL_MAX_TEXTURE_SIZE 16384. Rendering is currently in 2D mode.
Aborted (core dumped)
```

Now we fake a 2D array of wells, by adding another missing column:
```
{"plate": {
         "acquisitions": [{"id": 0, "name": "210305NAR005AAN"}],
         "columns": [
                 {"name": "07"},
                 {"name": "08"},
                 {"name": "09"},
                 {"name": "10"},
                 {"name": "11"}
                 ],
         "rows": [
                 {"name": "B"},
                 {"name": "C"}
                 ],
         "wells": [
                 {"path": "B/07"},
                 {"path": "B/11"}
                 ]
}}
```
In this case napari doesn't fail, and it shows the two wells in the correct position. This is already confusing.

Let's now add some more complexity now. All these tests were done with the napari window occupying half of my screen. Now, if I make it as large as the screen, the error may appear again _in all cases_. This is _very_ confusing!

**Comment by jluethi** [comment]
Have we ever run into this again @tcompa ? I've never seen this come up again with OME-Zarr file. 

Feel free to reopen if you keep seeing this.

**Comment by tcompa** [comment]
I tried to reproduce this now, and the error changed. We can keep this closed (nothing related to GL any more), but for sure there is some glitch in napari when the grid of wells is one-dimensional.

---

Steps to reproduce:
1. Prepare an OME-Zarr file with the two wells B03 and B05.
2. Display the plate with napari -> this incorrectly shows the two wells next to each other, instead of leaving the space for B04 empty.
3. Modify the plate .zattrs file, by adding a fake column 04 and a fake well B04.
4. Display the plate with napari -> this shows the two wells at the expected positions, but raises a `zarr.errors.ArrayNotFoundError: array not found at path %r' 'B/04/0/0'` error for the missing well.

**Comment by jluethi** [comment]
Ok, that is a different limitation. The question of how wells in a plate should be shown and how the user will know which well is which, is broader. Maybe we can start to address some of it when we start loading more varied wells in the plate reader (i.e. wells of different sizes).

According to the current spec, the metadata should only contain entries for wells that are present. And I'm not sure how strong napari-ome-zarr wants to have assumptions on the layouts following our regular plate layouts where B03 & B05 would not be neighbors. But worth a try eventually establishing that :)
