### ISSUE TITLE
Fix import error

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-tasks-core#542]
This is triggered by running fractal-demos example 01 with server 1.3.8a0, client 1.3.6a2, tasks 0.12.0a0 and python 3.10:
```
TASK ERROR:Task id: 5 (Cellpose Segmentation), e.workflow_task_order=4
TRACEBACK:
Traceback (most recent call last):
  File "/home/tommaso/Fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.12.0a0/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/cellpose_segmentation.py", line 25, in <module>
    import cellpose
  File "/home/tommaso/Fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.12.0a0/venv/lib/python3.10/site-packages/cellpose/__init__.py", line 1, in <module>
    from cellpose.version import version, version_str
  File "/home/tommaso/Fractal/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.12.0a0/venv/lib/python3.10/site-packages/cellpose/version.py", line 11, in <module>
    version = version("cellpose")
  File "/home/tommaso/miniconda3/envs/fractal-server-1.3.8a0/lib/python3.10/importlib/metadata/__init__.py", line 946, in version
    from devtools import debug
ModuleNotFoundError: No module named 'devtools'
```

**Comment by tcompa** [comment]
The same issue disappears if the server runs with python 3.9.

**Comment by tcompa** [comment]
This was clearly a local-environment issue, that conda did not make very evident.
Closing
